slides: /pipeline/metadata/sample_wsis.txt
slides_metadata: /pipeline/metadata/wsi_paths.txt
output_dir: /pipeline/output/patient_data_04_27
mask_model_path: /pipeline/model_weights/cellpose_model
encode_model_path: /pipeline/model_weights/representation_model_04_27.pth
classifier_path: /pipeline/model_weights/wbc_model_0225.pth
detect_and_infer: /pipeline/src/pipeline.py
n_threads: 8
device: cuda:1 # Change between 'cuda:0' and 'cuda:1' for two concurrent runs
verbose: '-v' # '-v' -> verbose | '' -> non-verbose
