name: deep_phenotyping
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python packages
  - python=3.9.7
  - numpy=1.22.4
  - pandas=1.3.5
  - scipy=1.7.3
  - matplotlib=3.5.1
  - ipython=8.18.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2

  # Development tools
  - debugpy=1.8.14
  - psutil=7.0.0

  # Image processing and ML
  - scikit-image=0.19.1
  - scikit-learn=1.5.2
  - h5py=3.11.0
  - tifffile=2024.8.30
  - pillow=11.2.1
  
  # Data analysis
  - numba=0.60.0
  - numexpr=2.10.0
  - seaborn=0.13.2
  
  # Utilities
  - pyyaml=6.0.2
  - requests=2.32.3
  - networkx=3.2.1
  - joblib=1.4.2
  - tqdm=4.67.1
  
  # Packages that need to be installed via pip
  - pip=24.2
  - pip:
    # GitHub package
    - git+https://github.com/actual-repo-owner/slide-image-utils.git
    
    # Image processing
    - cellpose==3.1.1.1
    - opencv-python-headless==4.11.0.86
    - imagecodecs==2024.12.30
    - imageio==2.37.0
    - fastremap==1.15.2
    - natsort==8.4.0
    
    # Deep learning
    - torch==2.3.0
    - torchvision==0.18.0
    - triton==2.3.0
    
    # Analysis tools
    - umap-learn==0.5.7
    - hdbscan==0.8.40
    - pyod==2.0.4
    
    # Pipeline tools
    - snakemake==7.32.0
    - wandb==0.19.10
    
    # Documentation
    - pdoc3>=0.10.0
